version: '3.4'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db

  seq:
    container_name: seq
    restart: unless-stopped
    image: datalust/seq:latest
    ports:
    - 5341:80
    volumes:
    - ./data/seq:/data
    environment:
    - DEFAULT_HOST=seq.drifterapps.com
    - VIRTUAL_HOST=seq.drifterapps.com
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=seq.drifterapps.com
    - LETSENCRYPT_EMAIL=info@drifterapps.com
    - ACCEPT_EULA=Y
  
networks:
  default:
    name: development-network
    driver: bridge
